services:
    _defaults:
        autowire: true
        autoconfigure: true

    KlapprothKoch\ContaoEventNewsCategories\:
        resource: '../src/'
        exclude:
            - '../src/ContaoManager/'
            - '../src/DependencyInjection/'
            - '../src/ContaoEventNewsCategoriesBundle.php'
